application: diarytype
version: 30
runtime: python
api_version: 1

default_expiration: "30d"

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  mime_type: text/plain

- url: /static
  static_dir: static

- url: /tinymce/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /task/.*
  script: main.py
  login: admin

- url: .*
  script: main.py

builtins:
  - datastore_admin: on

skip_files: |
    ^(.*/)?(
    (app\.yaml)|
    (app\.yml)|
    (index\.yaml)|
    (index\.yml)|
    (#.*#)|
    (.*~)|
    (.*\.py[co])|
    (.*/RCS/.*)|
    (\..*)|
    (nbproject)|
    )$
